name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:

  test:

    uses: $/.github/workflows/test.yml
    with:
      save-rust-cache: true
      test-macos: true

  test-windows-trampolines:

    uses: $/.github/workflows/test-windows-trampolines.yml
    with:
      trampoline-build: true

  build-dev-binaries:

    uses: $/.github/workflows/build-dev-binaries.yml
    with:
      save-rust-cache: true

  test-smoke:
    needs:
      - build-dev-binaries
    uses: $/.github/workflows/test-smoke.yml
    with:
      sha: ${{ github.sha }}

  test-integration:
    needs:
      - build-dev-binaries
    uses: $/.github/workflows/test-integration.yml
    secrets: inherit
    permissions:
      id-token: write
    with:
      sha: ${{ github.sha }}

  test-system:
    needs:
      - build-dev-binaries
    uses: $/.github/workflows/test-system.yml
    with:
      sha: ${{ github.sha }}

  test-ecosystem:
    needs:
      - build-dev-binaries
    uses: $/.github/workflows/test-ecosystem.yml
    with:
      sha: ${{ github.sha }}

  build-docker:

    uses: $/.github/workflows/build-docker.yml
    with:
      push-dev: false
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      packages: write
      attestations: write

  bench:

    uses: $/.github/workflows/bench.yml
    secrets: inherit
    with:
      save-rust-cache: true
